# Site Settings
title: "Bazen Haile - GIS & Remote Sensing"
description: "MSc GIS & Remote Sensing graduate showcasing geospatial projects and educational content"
url: "https://bazenhaile.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Bazen Haile"
  bio: "MSc GIS & Remote Sensing | Maynooth University Graduate | Geospatial Analyst"
  location: "Dublin, Ireland"
  email: "bazenhaileam@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bazenhaile"
    - label: "Portfolio"
      icon: "fas fa-fw fa-briefcase"
      url: "/portfolio/"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/yourprofile"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bazenhaile"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bazenhaileam@gmail.com"

# Navigation
main:
  - title: "Home"
    url: /
  - title: "About"
    url: /about/
  - title: "Portfolio"
    url: /portfolio/
  - title: "Remote Sensing"
    url: /remote-sensing/
  - title: "GIS Projects"
    url: /gis-projects/
  - title: "Learning Notes"
    url: /notes/
  - title: "Contact"
    url: /contact/

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
      sidebar:
        nav: "portfolio"

# Sidebar Navigation for Portfolio
portfolio:
  - title: "Project Details"
    children:
      - title: "Overview"
        url: "#project-overview"
      - title: "Technical Approach"
        url: "#technical-approach"
      - title: "Key Findings"
        url: "#key-findings"
      - title: "Impact & Applications"
        url: "#impact--applications"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# SEO and Social
social:
  type: Person
  name: Bazen Haile
  links:
    - "https://linkedin.com/in/yourprofile"
    - "https://github.com/bazenhaile"

# Analytics (uncomment when ready)
# google_analytics: "UA-XXXXXXXXX-X"
