# Site Settings
title: "Bazen Hailemelekt Amene - GIS & Remote Sensing Specialist"
description: "Dublin-based Maynooth University MSc graduate specializing in spatial analysis, remote sensing, and geospatial solutions for Ireland's environmental challenges."
url: "https://bazenhaile.github.io"
baseurl: ""

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "mint"

# Site Author
author:
  name: "Bazen Hailemelekt Amene"
  bio: "MSc GIS & Remote Sensing (Maynooth University) | Expertise in ArcGIS, QGIS, ERDAS Imagine | Passionate about geospatial innovation in Ireland."
  location: "Dublin, Ireland"
  email: "bazenhileam@gmail.com"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bazen-amene"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BazenHaile"
    - label: "Portfolio"
      icon: "fas fa-fw fa-briefcase"
      url: "/portfolio/"

# Site Footer
footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/bazen-amene"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BazenHaile"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:bazenhileam@gmail.com"
    - label: "Phone"
      icon: "fas fa-fw fa-phone"
      url: "tel:+353877882085"

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:name/
  experience:
    output: true
    permalink: /:collection/:name/
  education:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
  - scope:
      path: ""
      type: experience
    values:
      layout: single
      author_profile: false
      share: true
  - scope:
      path: ""
      type: education
    values:
      layout: single
      author_profile: false
      share: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Include pages
include:
  - _pages

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# SEO and Social
social:
  type: Person
  name: "Bazen Hailemelekt Amene"
  links:
    - "https://www.linkedin.com/in/bazen-amene"
    - "https://github.com/BazenHaile"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-XXXXXXXXX-X"  # Replace with your ID
